blogGetOne:
  type: object
  properties:
    id:
      type: string
      minLength: 24
      maxLength: 24
  required:
    - id
  additionalProperties: false
blogCreate:
  type: object
  properties:
    blogName:
      type: string
      minLength: 1
    blogDescription:
      type: string
      minLength: 1
  required:
    - blogName
    - blogDescription
  additionalProperties: false
blogUpdate:
  type: object
  properties:
    id:
      type: string
      minLength: 24
      maxLength: 24
    blogName:
      type: string
      minLength: 1
    blogDescription:
      type: string
      minLength: 1
  required:
    - id
    - blogName
    - blogDescription
  additionalProperties: false
blogDelete:
  type: object
  properties:
    id:
      type: string
      minLength: 24
      maxLength: 24
  required:
    - id
  additionalProperties: false
